name: news scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: run news script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python fetcher.py

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit logs to main
        run: |
          git add log.txt
          git commit -m "Log update: $(date)" || echo "No log changes"
          git push origin main

      - name: Deploy news to gh-pages
        run: |
          cp news.txt /tmp/news.txt
          
          git checkout gh-pages || git checkout --orphan gh-pages
          
          #git rm -rf . 
          
          mv /tmp/news.txt index.html
          
          git add index.html
          git commit -m "Web update: $(date)"
          git push origin gh-pages --force
